# Generated by Django 5.0.1 on 2024-02-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdle', '0002_auto_20230913_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='guess_count',
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='is_winner',
        ),
    ]
