# Generated by Django 5.0.1 on 2024-02-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birdle', '0005_guess_usergame_image_photographer_alter_game_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guess',
            name='game',
        ),
        migrations.RemoveField(
            model_name='guess',
            name='user',
        ),
    ]
