# Generated by Django 5.0.1 on 2024-03-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdle', '0007_alter_bird_species_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='guess',
            name='hint_used',
            field=models.BooleanField(null=True),
        ),
    ]
