# Generated by Django 5.0.1 on 2024-04-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdle', '0009_alter_guess_hint_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='birdregion',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='birdregion',
            name='region_name',
        ),
        migrations.AddField(
            model_name='birdregion',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='birdle.region'),
        ),
    ]
