# Generated by Django 5.0.1 on 2024-04-02 00:21

import birdle.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdle', '0010_region_remove_birdregion_region_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='region',
            field=models.ForeignKey(default=birdle.models.Region.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='birdle.region'),
        ),
    ]
