# Generated by Django 5.0.1 on 2026-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birdle", "0012_alter_game_date_alter_game_unique_together"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="birdregion",
            index=models.Index(fields=["region", "bird"], name="birdle_bird_region__7c1a95_idx"),
        ),
    ]
