# Generated by Django 5.0.1 on 2026-08-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birdle", "0013_birdregion_birdle_bird_region__7c1a95_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="bird",
            name="hint_general",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bird",
            name="hint_specific",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="bird",
            name="hint_vague",
            field=models.TextField(blank=True, default=""),
        ),
    ]
