# Generated by Django 5.2.17 on 2026-09-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birdle", "0014_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergame",
            name="is_archive",
            field=models.BooleanField(default=False),
        ),
    ]
