# Generated by Django 5.2.17 on 2026-09-07 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birdle", "0015_usergame_is_archive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=2, max_digits=5)),
                ("lng", models.DecimalField(decimal_places=2, max_digits=6)),
                ("species_count", models.PositiveIntegerField(default=0)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="birdle.region"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
