# Generated by Django 5.0.1 on 2026-08-09 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("birdle", "0015_backfill_profiles"),
        ("birdle", "0016_seed_world_region"),
    ]

    operations = []
