# Generated by Django 5.0.1 on 2026-08-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birdle", "0015_backfill_profiles"),
        ("birdle", "0016_seed_world_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="birdle.region",
            ),
        ),
    ]
